### ISSUE TITLE
Single quotes don't work for strings within a JSONPath

### ISSUE THREAD

**Issue by tkuhlman** [PaesslerAG/jsonpath#1]
When using this library I noticed that single quotes do not work within a JSONPath, specifically I was evaluating a path like `$.data.attributes[?(@.name=='title')].value` which fails but changing to double quotes around `title` like `$.data.attributes[?(@.name=="title")].value` works fine. I'm not sure if the JSONPath spec addresses quoting at all but the evaluator at http://jsonpath.com/ handles the single quotes fine.

**Comment by kairichard** [comment]
Thanks for reporting the issue - we have a look at the spec and fix it accordingly. //cc @paessler-jekeller

**Comment by paessler-jekeller** [comment]
jsonpath has no formal specification and the (script) language jsonpath is used in is also part of jsonpath. http://jsonpath.com/ uses js as script language so " and ' works fine. But yes, it would be nice to have them.

**Comment by generikvault** [comment]
I've wrote a gval language extension for single Quotes.
Just include it to the language and singlequotes will be parsed.

github.com/generikvault/gvalstrings
