### ISSUE TITLE
Is there a way to get the path from the fetch

### ISSUE THREAD

**Issue by moshevi** [PaesslerAG/jsonpath#10]
If I look at 
`{
  "a": {
    "b": {
      "c": 1,
      "d": 2
    }
  }
}`

and running this expression '$..c' I will get the value 1.
Is there a way to get c full path as well (like '$a.b.c') ?

**Comment by generikvault** [comment]
Hi moshevi,

in this package is an extension for placeholders. This isn't official json path anymore but it helps to access the keys.

The path `{#: $..x}` will return a map[string]interface{} from jsonpath to value. In this case $["a"]["b"]["c"]

**Comment by moshevi** [comment]
Hi @generikvault 
Can you send me a code sample for that?
Thanks.

**Comment by generikvault** [comment]
The placeholder `#` without a number is a hack and it works only for the wildcard parts so you have to add the c manually:

`	builder := jsonpath.PlaceholderExtension()

	path, err := builder.NewEvaluable(`{#: $..c}`)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	v := interface{}(nil)
	err = json.Unmarshal([]byte(`{ "a": { "b": { "c": 1, "d": 2 } } }`), &v)

	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	devices, err := path(context.Background(), v)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	for device, name := range devices.(map[string]interface{}) {
		fmt.Printf("%s -> %v\n", device, name)
	}

	// Unordered output:
	// $["a"]["b"] -> 1`

Actually palceholders should be used like `#0` or `#1` to access the nth key or in case of `..` an array of the keys. (see the gval example in godoc)

**Comment by moshevi** [comment]
Thanks @generikvault

**Comment by moshevi** [comment]
@generikvault Is there any samples for using regex for jsonpath or gval?
