### ISSUE TITLE
Does this library support regular expressions? or will it in the future?

### ISSUE THREAD

**Issue by moshevi** [PaesslerAG/jsonpath#11]

**Comment by generikvault** [comment]
Merge jsonpath with gval.Text() or gval.Full() for Regex support. For latter is in example in the godoc.

You find regex operators in the godoc of gval.Text(): https://godoc.org/github.com/PaesslerAG/gval#Text

**Comment by moshevi** [comment]
But currently it's not supported out of the box as jsonpath expression?

**Comment by generikvault** [comment]
You can use it via:
`builder := gval.Full(jsonpath.Language())

path, err := builder.NewEvaluable("$..[?@ =~ \"[fF][oO]+\"]")`

RegEx is not part of the JSonPath specification so I'm not planning to add it into `jsonpath.Language()`

**Comment by moshevi** [comment]
Thanks generikvault for your answers

**Comment by moshevi** [comment]
@generikvault Just another filter question:
Can I filter an object attribute value or just an array one.
For example I have this JSON:
{"a":1, "b":2} How can I get a yes/no one-liner JsonPath expression that will return true for a==1 and false for a==2 ?

**Comment by generikvault** [comment]
What do you want to achieve?
`$.a == 1` returns true or false as descibed.

If you want to filter for a specific Object let's say in `{"x":{"a":1, "b":2},"y":{"a":2, "b":3}}` you can do this with `$[@.a == 1]`

**Comment by moshevi** [comment]
Thanks @generikvault I misuse it. It works.

**Comment by moshevi** [comment]
If I'll change the json to {"a":1.23, "b":2} this will return false: $.a == 1.23

**Comment by moshevi** [comment]
Thanks @generikvault
