### ISSUE TITLE
Missing 'v' in tag for version 0.1.1

### ISSUE THREAD

**Issue by cukuriwaray** [PaesslerAG/jsonpath#17]
Hi, thank you for the library.

I am trying out to upgrade version from v0.1.0 to 0.1.1

Execution of `go get -u github.com/PaesslerAG/jsonpath` do nothing.

Manual change of the version in go.mod file to v0.1.1 and run project produces the error:

```
go: finding github.com/PaesslerAG/jsonpath v0.1.1
go: github.com/PaesslerAG/jsonpath@v0.1.1: unknown revision v0.1.1
go: error loading module requirements
```
Usage of version string '0.1.1' without leading 'v' is forbidden in go.mod.

Am I missing something?

go version go1.11.5 linux/amd64

Thanks

**Comment by generikvault** [comment]
Thanks. I've added the v
